### PR TITLE
Reworked Rdio Api Demo with Bootstrap and Cleanup Styles

### PR DESCRIPTION
**Pull request by pfarrar1**
Cleaned up some of the styles of the Rdio Web Playback API Demo

### CODE REVIEW

**Comment by pfarrar1** [comment]
screen shot 2014-03-01 at 7 23 08 pm

**Comment by dasevilla** [comment]
Thanks for the contribution! I'll review it this week.

**Comment by dasevilla** [comment]
Thanks!

**Comment by pfarrar1** [comment]
cool. I'm glad i could help out

**Pull request merged**
